#!/bin/bash

### This script is called before the user upgrades the application.


apt update
apt install --only-upgrade -y open-vm-tools
[ $? -ne 0 ] && echo "Failed to upgrade open-vm-tools package." >$TRIM_TEMP_LOGFILE && exit 1

exit 0
