#!/bin/bash

### This script is called after the user installs the application.

ARCH=$(uname -m)
if [ ! -x "${TRIM_APPDEST}/server/ttyd.${ARCH:-}" ]; then
  echo "${ARCH} is not supported." >$TRIM_TEMP_LOGFILE
  exit 1
fi

exit 0
