#!/bin/bash

### This script is called before the user installs the application.

apt update
apt install -y --no-install-recommends tmux
[ $? -ne 0 ] && echo "Failed to install tmux package." >$TRIM_TEMP_LOGFILE && exit 1

exit 0
