#!/bin/bash

LOG_FILE="${TRIM_PKGVAR}/info.log"
PID_FILE="${TRIM_PKGVAR}/app.pid"

ARCH=$(uname -m)
# BIN_PATH="${TRIM_APPDEST}/server/${ARCH:-}/usr/bin"
# LIB_PATH="${TRIM_APPDEST}/server/${ARCH:-}/usr/lib/:${TRIM_APPDEST}/server/${ARCH:-}/usr/lib/${ARCH:-}-linux-gnu"
# export PATH="${BIN_PATH}:${PATH:-}"
# export LD_LIBRARY_PATH="${LIB_PATH}:${LD_LIBRARY_PATH:-}"

locale -a 2>/dev/null | tr '[:upper:]' '[:lower:]' | grep -Eq "^zh_cn\.[utf-8|utf8]$" || localedef -i zh_CN -f UTF-8 zh_CN.UTF-8 >/dev/null 2>&1 || true

tmux new-session -d -s __init__
[ "${wizard_user_login:-root}" = "login" ] && tmux set-option -g default-command 'login' # 登录默认命令
tmux set-option -g utf8 on # 支持utf8
tmux set-option -g status-utf8 on # 状态栏支持utf8
tmux set-option -g history-limit 50000 # 历史记录条数
tmux set-option -g set-clipboard on # 开启剪贴板同步
tmux set-option -g mouse on # 开启鼠标支持
[ "${wizard_right_type:-tmux}" = "tmux" ] || tmux unbind -T root MouseDown3Pane # 禁用鼠标滚动
tmux kill-session -t __init__

TTYDARGS=()
TTYDARGS+=(${TRIM_APPDEST}/server/ttyd.${ARCH:-} -a -W)
TTYDARGS+=(-i "${TRIM_APPDEST}/fn-terminal.sock" -b "/app/fn-terminal")
[ "${wizard_right_type:-tmux}" = "tmux" ] && TTYDARGS+=(-I "${TRIM_APPDEST}/server/ttyd-index.html")
TTYDARGS+=(-t titleFixed=fnOS -t allow-clipboard-read=true -t allow-clipboard-write=true -t rendererType=canvas)
TTYDARGS+=(tmux -u new -A -s terminal)
[ "${wizard_user_login:-root}" = "login" ] && TTYDARGS+=(login)

# write the command to start your program here
CMD="env LANG=zh_CN.UTF-8 LC_ALL=zh_CN.UTF-8 TERM=xterm-256color ${TTYDARGS[*]}"

log_msg() {
  echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" >>${LOG_FILE}
}

start_process() {
  if status; then
    return 0
  fi

  log_msg "Starting process ..."
  # run cmd to start process
  rm -f "${TRIM_APPDEST}/fn-terminal.sock"
  bash -c "${CMD}" >>${LOG_FILE} 2>&1 &
  # write pid to pidfile
  printf "%s" "$!" >${PID_FILE}
  # log_msg "CMD = ${CMD}"
  # log_msg "pid = $!"
  return 0
}

stop_process() {
  log_msg "Stopping process ..."

  if [ -r "${PID_FILE}" ]; then
    pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')

    log_msg "pid=${pid}"
    if ! check_process "${pid}"; then
      # process not exist, delete pidfile
      tmux kill-session -t terminal 2>/dev/null || true
      rm -f "${PID_FILE}"
      rm -f "${TRIM_APPDEST}/fn-terminal.sock"
      log_msg "remove pid file 1"
      return
    fi

    log_msg "send TERM signal to PID:${pid}..."
    kill -TERM ${pid} >>${LOG_FILE} 2>&1

    local count=0
    while check_process "${pid}" && [ $count -lt 10 ]; do
      sleep 1
      count=$((count + 1))
      log_msg "waiting process terminal... (${count}s/10s)"
    done

    if check_process "${pid}"; then
      log_msg "send KILL signal to PID:${pid}..."
      kill -KILL "${pid}"
      sleep 1
      rm -f "${PID_FILE}"
    else
      log_msg "process killed... "
    fi
  fi
  tmux kill-session -t terminal 2>/dev/null || true
  return 0
}

check_process() {
  local pid=$1
  if kill -0 "${pid}" 2>/dev/null; then
    return 0 # process exist
  else
    return 1 # process not exist
  fi
}

status() {
  if [ -f "${PID_FILE}" ]; then
    pid=$(head -n 1 "${PID_FILE}" | tr -d '[:space:]')
    if check_process "${pid}"; then
      return 0
    else
      # Process is not running but pidfile exists - clean it up
      rm -f "${PID_FILE}"
    fi
  fi

  return 1
}

case $1 in
  start)
    # run start command. exit 0 if success, exit 1 if failed
    start_process
    ;;
  stop)
    # run stop command. exit 0 if success, exit 1 if failed
    stop_process
    ;;
  status)
    # check application status command. exit 0 if running, exit 3 if not running
    if status; then
      exit 0
    else
      exit 3
    fi
    ;;
  *)
    exit 1
    ;;
esac
