#!/bin/bash

### This script is called after the user installs the application.

chmod +x ${TRIM_APPDEST}/ui/*.cgi 2>/dev/null || true
chmod +x ${TRIM_APPDEST}/www/*.cgi 2>/dev/null || true

# fnOS v1.1.28 Fix regulatory.db issue
# for F in "/usr/lib/firmware/regulatory.db" "/usr/lib/firmware/regulatory.db.p7s"; do
#   if [ "$(readlink -f "${F}")" = "${F}-debian" ] && [ -f "${F}-upstream" ]; then
#     rm -f "${F}"
#     ln -vsf "${F}-upstream" "${F}"
#     [ $? -ne 0 ] && {
#       echo "Failed to link ${F}-upstream to ${F}" >$TRIM_TEMP_LOGFILE
#       exit 1
#     }
#   fi
# done

exit 0
