#!/bin/bash

### This script is called before the user upgrades the application.

apt update
apt install --only-upgrade -y iw
[ $? -ne 0 ] && echo "Failed to upgrade iw package." >$TRIM_TEMP_LOGFILE && exit 1

exit 0
