#!/bin/bash

### This script is called after the user upgrades the application.

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "${SCRIPT_DIR}/_functions"

if [ ! -x "${INFLUXDB_BIN}" ]; then
    echo "Downloading InfluxDB..." >$TRIM_TEMP_LOGFILE 2>&1
    download_influxdb
    if [ $? -ne 0 ]; then
        echo "Failed to download InfluxDB. Please check your internet connection." >$TRIM_TEMP_LOGFILE 2>&1
        exit 1
    fi
fi

exit 0
