#!/bin/bash
# Chinese translation patch for Scrutiny Web frontend
# Applied once on first start (creates .translated marker file)

WEB_DIR="${1:-.}"
MARKER="${WEB_DIR}/.translated"

if [ -f "${MARKER}" ]; then
    exit 0
fi

echo "Applying Chinese translation to Scrutiny frontend..."

cd "${WEB_DIR}" || exit 1

# Helper: translate both "X" and " X " formats
# Usage: tr_both "English" "Chinese"
tr_both() {
    local en="$1"
    local zh="$2"
    for f in main-*.js chunk-*.js; do
        [ -f "$f" ] || continue
        sed -i "s#\"${en}\"#\"${zh}\"#g" "$f"
        sed -i "s#\" ${en} \"#\" ${zh} \"#g" "$f"
    done
}

# Helper: translate only in a specific chunk file
# Usage: tr_chunk_NAME "English" "Chinese"
tr_chunk_SXF454OX() {
    local en="$1"
    local zh="$2"
    for f in chunk-SXF454OX.js; do
        [ -f "$f" ] || continue
        sed -i "s#\"${en}\"#\"${zh}\"#g" "$f"
    done
}

# Navigation & Common
tr_both "Dashboard" "仪表盘"
tr_both "Drives" "硬盘"
tr_both "Details" "详情"
tr_both "Settings" "设置"
tr_both "Home" "首页"
tr_both "Logout" "退出登录"
tr_both "Sign in" "登录"
tr_both "Save" "保存"
tr_both "Cancel" "取消"
tr_both "Remove" "删除"
tr_both "Delete" "删除"
tr_both "Delete Device" "删除设备"
tr_both "Close" "关闭"
tr_both "Sort By" "排序方式"
tr_both "Reset Zoom" "重置缩放"
tr_both "Zoom In" "放大"
tr_both "Zoom Out" "缩小"
tr_both "Toggle theme" "切换主题"
tr_both "Dark" "深色"
tr_both "Light" "浅色"
tr_both "Copy" "复制"
tr_both "Copied" "已复制"
tr_both "Optional" "可选"
tr_both "Archive" "归档"
tr_both "Unarchive" "取消归档"
tr_both "Archived" "已归档"
tr_both "Open" "打开"
tr_both "All" "全部"
tr_both "N/A" "无"
tr_both "Day" "天"
tr_both "Week" "周"
tr_both "Month" "月"
tr_both "Year" "年"
tr_both "day" "天"
tr_both "week" "周"
tr_both "month" "月"
tr_both "year" "年"
tr_both "forever" "永久"
tr_both "Device" "设备"
tr_both "All Drives" "所有硬盘"
tr_both "No Data" "暂无数据"
tr_both "Drive health at a glance" "硬盘健康概览"
tr_both "not yet implemented" "尚未实现"
tr_both "Notification Channels" "通知渠道"
tr_both "No notification channels configured. Add one below, or configure notify.urls in scrutiny.yaml." "未配置通知渠道。请在下方添加，或在 scrutiny.yaml 中配置 notify.urls。"
tr_both "Missed Ping Timeout Override (minutes)" "心跳超时覆盖（分钟）"
tr_both "Override the global missed ping timeout for this device. 0 = use global (60 min)" "覆盖此设备的全局心跳超时。0 = 使用全局设置（60分钟）"

# Status
tr_both "Critical" "严重"
tr_both "Warning" "警告"
tr_both "Passed" "通过"
tr_both "Failed" "失败"
tr_both "Healthy" "健康"
tr_both "Unknown" "未知"
tr_both "All systems healthy" "所有系统正常"
tr_both "ONLINE" "在线"
tr_both "OFFLINE" "离线"
tr_both "PENDING" "待处理"
tr_both "REMOVED" "已移除"
tr_both "UNAVAIL" "不可用"
tr_both "Status" "状态"

# Drive Info
tr_both "Device Type" "设备类型"
tr_both "Device Model" "设备型号"
tr_both "Firmware Version" "固件版本"
tr_both "LU WWN Device Id" "LU WWN 设备ID"
tr_both "Temperature" "温度"
tr_both "Celsius" "摄氏度"
tr_both "Capacity" "容量"
tr_both "Capacity History" "容量历史"
tr_both "Serial Number" "序列号"
tr_both "Serial ID" "序列号ID"
tr_both "Interface" "接口"
tr_both "Rotation Rate" "转速"
tr_both "Powered On" "已运行"
tr_both "Power on Hours" "运行小时数"
tr_both "Power Cycle Count" "开关机次数"
tr_both "Power Cycles" "开关机次数"
tr_both "Powered On Format" "运行时间格式"
tr_both "Score" "评分"
tr_both "Host ID" "主机ID"
tr_both "Collector Version" "采集器版本"
tr_both "Total" "总计"
tr_both "Used" "已使用"
tr_both "Sector" "扇区"
tr_both "Value" "值"
tr_both "Attribute" "属性"
tr_both "Attribute ID" "属性ID"
tr_both "Show all attributes" "显示所有属性"
tr_both "Show critical attributes" "显示关键属性"
tr_both "Custom Threshold" "自定义阈值"
tr_both "Custom Label" "自定义标签"
tr_both "Trend" "趋势"
tr_both "Click to view history" "点击查看历史"
tr_both "View Details" "查看详情"
tr_both "Last Updated on" "最后更新于"
tr_both "Protocol" "协议"
tr_both "Worst" "最差"
tr_both "Worst/Thresh" "最差/阈值"
tr_both "Worst:" "最差:"
tr_both "Ideal:" "理想:"
tr_both "Threshold:" "阈值:"
tr_both "Threshold Data" "阈值数据"
tr_both "Warn Above" "高于警告"
tr_both "Size" "大小"
tr_both "Weight" "权重"
tr_both "passed" "通过"
tr_both "warn" "警告"
tr_both "failed" "失败"
tr_both "Pre-Fail" "预失败"
tr_both "Old-Age" "老化"
tr_both "Name" "名称"
tr_both "History" "历史"
tr_both "visible" "可见"
tr_both "hidden" "隐藏"
tr_both "S.M.A.R.T" "S.M.A.R.T"
tr_both "S.M.A.R.T " "S.M.A.R.T "
tr_both "S.M.A.R.T NVMe Attributes" "S.M.A.R.T NVMe 属性"
tr_both "S.M.A.R.T SCSI Attributes" "S.M.A.R.T SCSI 属性"
tr_both "SMART Attribute" "SMART 属性"
tr_both "Attribute Name" "属性名称"

# Workload & Performance
tr_both "Workload" "负载"
tr_both "Workload Insights" "负载洞察"
tr_both "Daily Writes" "每日写入"
tr_both "Daily Reads" "每日读取"
tr_both "R/W Ratio" "读写比"
tr_both "Intensity" "强度"
tr_both "Endurance" "耐久度"
tr_both "Est. Remaining" "预计剩余"
tr_both "Sequential Throughput" "顺序吞吐量"
tr_both "Sequential Read" "顺序读取"
tr_both "Sequential Write" "顺序写入"
tr_both "Random Read" "随机读取"
tr_both "Random Write" "随机写入"
tr_both "Random IOPS" "随机 IOPS"
tr_both "Seq Read" "顺序读"
tr_both "Seq Write" "顺序写"
tr_both "Rand Read IOPS" "随机读 IOPS"
tr_both "Rand Write IOPS" "随机写 IOPS"
tr_both "Read Latency" "读取延迟"
tr_both "Write Latency" "写入延迟"
tr_both "Avg Latency" "平均延迟"
tr_both "TBs Read" "TB 读取"
tr_both "TBs Written" "TB 写入"
tr_both "No Workload Data Available" "无负载数据"
tr_both "Drive activity rates intensity and endurance" "硬盘活动率、强度和耐久度"
tr_both "Temperature history for each device" "各设备温度历史"

# SMART Attributes
tr_both "Reallocated Sectors Count" "重新分配扇区计数"
tr_both "Current Pending Sector Count" "当前待处理扇区计数"
tr_both "Load Cycle Count" "加载循环计数"
tr_both "Media Errors" "介质错误"
tr_both "Media Wearout Indicator" "介质磨损指标"
tr_both "Percentage Used" "使用百分比"
tr_both "Endurance Remaining" "剩余耐久度"
tr_both "Available Spare" "可用备用空间"
tr_both "Available Reserved Space" "可用保留空间"
tr_both "Critical Warning" "严重警告"
tr_both "Command Timeout" "命令超时"
tr_both "Controller Busy Time" "控制器忙碌时间"
tr_both "Data Units Read" "数据单元读取"
tr_both "Data Units Written" "数据单元写入"
tr_both "Host Reads" "主机读取"
tr_both "Host Writes" "主机写入"
tr_both "Life Left" "剩余寿命"
tr_both "Unsafe Shutdowns" "不安全关机"
tr_both "Unexpected Power Loss Count" "意外断电次数"
tr_both "Power Loss Protection Failure" "断电保护失败"
tr_both "Program Fail Count Total" "编程失败计数"
tr_both "Erase Fail Count" "擦除失败计数"
tr_both "Average erase count" "平均擦除计数"
tr_both "Good Block Count" "良好块计数"
tr_both "SSD Wear Leveling Count" "SSD 磨损均衡计数"
tr_both "SSD Wearout Health" "SSD 磨损健康"
tr_both "Read Error Rate" "读取错误率"
tr_both "Seek Error Rate" "寻道错误率"
tr_both "Hardware ECC Recovered" "硬件 ECC 恢复"
tr_both "Spin Retry Count" "主轴重试计数"
tr_both "Throughput Performance" "吞吐性能"
tr_both "UltraDMA CRC Error Count" "UltraDMA CRC 错误计数"
tr_both "Reported Uncorrectable Errors" "报告的不可纠正错误"
tr_both "Reallocation Event Count" "重新分配事件计数"
tr_both "High Fly Writes" "高飞写入"
tr_both "Temperature Difference" "温度差异"
tr_both "Checksum Errors" "校验和错误"
tr_both "Read Errors" "读取错误"
tr_both "Write Errors" "写入错误"
tr_both "Reads" "读取"
tr_both "Writes" "写入"
tr_both "Numb Err Log Entries" "错误日志条目数"
tr_both "Start/Stop Count" "启动/停止计数"
tr_both "Spin-Up Time" "主轴启动时间"
tr_both "Spin High Current" "主轴高电流"
tr_both "Spin Buzz" "主轴嗡鸣"
tr_both "Power-Off Retract Cycle" "断电缩回循环"
tr_both "Power-off Retract Count" "断电缩回计数"
tr_both "Load Cycle Count" "加载循环计数"
tr_both "Offline Seek Performance" "离线寻道性能"
tr_both "Shock During Write" "写入时震动"
tr_both "Vibration During Write" "写入时振动"
tr_both "Thermal Asperity Rate" "热粗糙率"
tr_both "Torque Amplification Count" "扭矩放大计数"
tr_both "G-Sense Error Rate" "G-Sense 错误率"
tr_both "Soft Read Error Rate" "软读取错误率"
tr_both "Soft ECC Correction" "软 ECC 纠正"
tr_both "Run Out Cancel" "溢出取消"
tr_both "Read Channel Margin" "读取通道裕量"
tr_both "Read Error Retry Rate" "读取错误重试率"
tr_both "Read Correction Algorithm Invocations" "读取纠正算法调用"
tr_both "Read Errors Corrected by ECC Delayed" "ECC 延迟纠正的读取错误"
tr_both "Read Errors Corrected by ECC Fast" "ECC 快速纠正的读取错误"
tr_both "Read Errors Corrected by ReReads/ReWrites" "重读/重写纠正的读取错误"
tr_both "Read Total Errors Corrected" "读取总纠正错误"
tr_both "Read Total Uncorrected Errors" "读取总不可纠正错误"
tr_both "Write Correction Algorithm Invocations" "写入纠正算法调用"
tr_both "Write Errors Corrected by ECC Delayed" "ECC 延迟纠正的写入错误"
tr_both "Write Errors Corrected by ECC Fast" "ECC 快速纠正的写入错误"
tr_both "Write Errors Corrected by ReReads/ReWrites" "重读/重写纠正的写入错误"
tr_both "Write Total Errors Corrected" "写入总纠正错误"
tr_both "Write Total Uncorrected Errors" "写入总不可纠正错误"
tr_both "Total LBAs Read" "总 LBA 读取"
tr_both "Total LBAs Written" "总 LBA 写入"
tr_both "Total LBAs Read Expanded" "总 LBA 读取（扩展）"
tr_both "Total LBAs Written Expanded" "总 LBA 写入（扩展）"
tr_both "Warning Temp Time" "警告温度时间"
tr_both "SSD Program Fail Count" "SSD 编程失败计数"
tr_both "SSD Erase Fail Count" "SSD 擦除失败计数"
tr_both "Wear Range Delta" "磨损范围增量"
tr_both "Good Block Count" "良好块计数"
tr_both "Average erase count" "平均擦除计数"
tr_both "Total count of LBAs written" "LBA 总写入计数"
tr_both "Uncorrected read errors reported to the operating system" "报告给操作系统的不可纠正读取错误"
tr_both "Contains a normalized percentage" "包含标准化百分比"
tr_both "Unknown Attribute Name" "未知属性名"
tr_both "Western Digital attribute" "西部数据属性"
tr_both "Pre-Fail attribute used at least in Samsung devices" "三星设备中至少使用过的预失败属性"
tr_both "Retrieve SCT Temperature History" "获取 SCT 温度历史"

# Notifications
tr_both "Notifications" "通知"
tr_both "Notifications muted" "通知已静音"
tr_both "Unmute notifications" "取消静音通知"
tr_both "Unmute" "取消静音"
tr_both "Add Notification Channel" "添加通知渠道"
tr_both "Send test notification" "发送测试通知"
tr_both "Test Push" "测试推送"
tr_both "Repeat Notifications" "重复通知"
tr_both "Quiet Hours Start" "静默时段开始"
tr_both "Quiet Hours End" "静默时段结束"
tr_both "Notify on Collector smartctl Errors" "采集器 smartctl 错误时通知"
tr_both "Notify on Missed Collector Ping" "采集器心跳丢失时通知"
tr_both "Alert when a collector stops sending data" "采集器停止发送数据时告警"
tr_both "SMTP Email" "SMTP 邮件"
tr_both "SMTP Host" "SMTP 主机"
tr_both "To Address" "收件地址"
tr_both "Slack Webhook URL" "Slack Webhook URL"
tr_both "Bot Token" "机器人 Token"
tr_both "Chat ID" "聊天 ID"
tr_both "API Token" "API Token"
tr_both "Custom Shoutrrr URL" "自定义 Shoutrrr URL"
tr_both "Uptime Kuma Push Monitor" "Uptime Kuma 推送监控"
tr_both "Push URL" "推送 URL"
tr_both "Push health status to Uptime Kuma" "推送健康状态到 Uptime Kuma"
tr_both "Test push sent successfully." "测试推送发送成功。"
tr_both "Test push failed. Check the push URL and try again." "测试推送失败。请检查推送 URL 后重试。"
tr_both "Push Interval (seconds)" "推送间隔（秒）"
tr_both "Repeat Notification Cooldown (minutes)" "重复通知冷却（分钟）"
tr_both "Telegram" "Telegram"
tr_both "Discord" "Discord"
tr_both "Paste the full Discord webhook URL from channel settings" "粘贴频道设置中的完整 Discord webhook URL"
tr_both "Paste the full Slack incoming webhook URL" "粘贴完整的 Slack incoming webhook URL"
tr_both "Slack" "Slack"
tr_both "Shoutrrr URL" "Shoutrrr URL"
tr_both "Sign in with Password" "密码登录"
tr_both "Sign in with Token" "Token 登录"
tr_both "Sent" "已发送"

# Settings & Config
tr_both "Scrutiny Settings" "Scrutiny 设置"
tr_both "Application configuration" "应用配置"
tr_both "SMART Attribute Overrides" "SMART 属性覆盖"
tr_both "Add New Override" "添加新覆盖"
tr_both "Add Override" "添加覆盖"
tr_both "Override active" "覆盖已激活"
tr_both "Remove override" "移除覆盖"
tr_both "Reset device status to passed" "重置设备状态为通过"
tr_both "Reset Status" "重置状态"
tr_both "Plan Replacement" "计划更换"
tr_both "Replacement Risk" "更换风险"
tr_both "Replace Soon" "建议更换"
tr_both "Scheduled Reports" "定时报告"
tr_both "Weekly Report" "每周报告"
tr_both "PDF Generation" "PDF 生成"
tr_both "Save PDF reports to disk" "保存 PDF 报告到磁盘"
tr_both "Configure automated health report delivery" "配置自动健康报告发送"
tr_both "Configure ignored attributes and custom thresholds" "配置忽略的属性和自定义阈值"
tr_both "Configure where notifications are sent" "配置通知发送位置"
tr_both "No attribute overrides configured" "未配置属性覆盖"
tr_both "PDF Save Directory" "PDF 保存目录"
tr_both "Weekly Report Time" "每周报告时间"
tr_both "Resume and send queued digest at this time" "恢复并在此时发送排队的摘要"
tr_both "Performance Benchmarks" "性能基准"
tr_both "Status (Failed First)" "状态（失败优先）"
tr_both "Status (Passed First)" "状态（通过优先）"
tr_both "Temperature (Coolest First)" "温度（最低优先）"
tr_both "Temperature (Hottest First)" "温度（最高优先）"
tr_both "Title (A-Z)" "名称（A-Z）"
tr_both "Title (Z-A)" "名称（Z-A）"
tr_both "SI Units (GB)" "SI 单位 (GB)"
tr_both "US Dollar" "美元"
tr_both "Scientific" "科学"
tr_both "Percent" "百分比"
tr_both "Pattern" "模式"
tr_both "Token" "令牌"
tr_both "Pool" "池"
tr_both "ZFS" "ZFS"
tr_both "SANITIZE" "清理"
tr_both "SCSI" "SCSI"
tr_both "Override:" "覆盖:"
tr_both "Zone:" "区域:"
tr_both "Dark Mode" "深色模式"
tr_both "System" "系统"
tr_both "Display Title" "显示标题"
tr_both "File Size" "文件大小"
tr_both "Binary Units (GiB)" "二进制单位 (GiB)"
tr_both "Humanize" "人性化"
tr_both "Line stroke" "线条样式"
tr_both "Smooth" "平滑"
tr_both "Device Status - Thresholds" "设备状态 - 阈值"
tr_both "Both" "两者"
tr_both "Notify - Level" "通知 - 级别"
tr_both "Fail" "仅失败"
tr_both "Notify - Filter Attributes" "通知 - 过滤属性"
tr_both "Always" "始终"
tr_both "Enabled" "启用"
tr_both "Disabled" "禁用"
tr_both "Fail Above" "失败高于"
tr_both "Device WWN (optional)" "设备 WWN（可选）"
tr_both "Heartbeat Notifications" "心跳通知"
tr_both "Master toggle for all scheduled reports" "所有定时报告的主开关"

# ZFS
tr_both "ZFS Pools" "ZFS 池"
tr_both "ZFS pool health at a glance" "ZFS 池健康概览"
tr_both "Virtual Device Tree" "虚拟设备树"
tr_both "No vdev information available" "无 vdev 信息"

# Misc
tr_both "Activity Spike Detected" "检测到活动峰值"
tr_both "A friendly name to identify this drive" "用于标识此硬盘的友好名称"
tr_both "Only when the value has changed" "仅当值发生变化时"
tr_both "Config file overrides cannot be deleted from UI" "配置文件覆盖无法从界面删除"
tr_both "Password" "密码"
tr_both "Username" "用户名"
tr_both "Port" "端口"
tr_both "Type" "类型"
tr_both "Source" "来源"
tr_both "Export" "导出"
tr_both "Forever" "永久"
tr_both "Critical CompTime" "关键完成时间"

# Additional SMART attribute names (from main JS metadata)
tr_both "Current Helium Level" "当前氦气水平"
tr_both "Data Address Mark errors" "数据地址标记错误"
tr_both "Disk Shift" "磁盘偏移"
tr_both "End-to-End error" "端到端错误"
tr_both "Flying Height" "飞行高度"
tr_both "Free Fall Events" "自由落体事件"
tr_both "Free Fall Protection" "自由落体保护"
tr_both "GMR Head Amplitude" "GMR 磁头振幅"
tr_both "Grown Defect List" "增长缺陷列表"
tr_both "G-sense Error Rate" "G-Sense 错误率"
tr_both "Head Flying Hours" "磁头飞行小时"
tr_both "Head Stability" "磁头稳定性"
tr_both "Height" "高度"
tr_both "Induced Op-Vibration Detection" "感应操作振动检测"
tr_both "Load Friction" "加载摩擦"
tr_both "Load/Unload Cycle Count" "加载/卸载循环计数"
tr_both "Load/Unload Retry Count" "加载/卸载重试计数"
tr_both "Loaded Hours" "加载小时数"
tr_both "Minimum Spares Remaining" "最小剩余备用"
tr_both "Multi-Zone Error Rate" "多区域错误率"
tr_both "Newly Added Bad Flash Block" "新增坏闪存块"
tr_both "Recalibration Retries or Calibration Retry Count" "重新校准重试计数"
tr_both "SATA Downshift Error Count or Runtime Bad Block" "SATA 降速错误计数"
tr_both "Seek Time Performance" "寻道时间性能"
tr_both "Spin Up Time" "主轴启动时间"
tr_both "Unused Reserved Block Count Total" "未使用保留块总数"
tr_both "Used Reserved Block Count Total" "已使用保留块总数"

# Device detail page (chunk-SXF454OX)
tr_both "Attribute actions" "属性操作"
tr_both "Device Label" "设备标签"
tr_both "Device settings" "设备设置"
tr_both "Device Settings" "设备设置"
tr_both "Device UUID" "设备 UUID"
tr_both "Failed to load device details:" "加载设备详情失败："
tr_both "Failed to remove override:" "移除覆盖失败："
tr_both "Failed to save override:" "保存覆盖失败："
tr_both "Failure %" "失败 %"
tr_both "Failure Rate:" "失败率："
tr_both "Forced " "已强制 "
tr_both "Force passed" "强制通过"
tr_both "Force Status" "强制状态"
tr_both "Ignore attribute" "忽略属性"
tr_both "Ignored" "已忽略"
tr_both "Manufacturer" "制造商"
tr_both "Mixed R/W" "混合读写"
tr_both "Model Family" "型号系列"
tr_both "Monitor" "监控"
tr_both "Norm" "标准化"
tr_both "Normalized" "标准化值"
tr_both "Mute notifications" "静音通知"

# Dashboard page (chunk-IKBCTKEQ)
tr_both "No Devices Detected!" "未检测到设备！"
tr_both "This will remove the device and all historical data from Scrutiny. " "此操作将从 Scrutiny 中删除该设备及所有历史数据。"
tr_both "Health" "健康"

# Settings page (chunk-7USPKHVX)
tr_both "Age (Newest First)" "使用时间（最新优先）"
tr_both "Age (Oldest First)" "使用时间（最旧优先）"
tr_both "Capacity (Largest First)" "容量（最大优先）"
tr_both "Capacity (Smallest First)" "容量（最小优先）"
tr_both "Check Interval (minutes)" "检查间隔（分钟）"
tr_both "Daily Report" "每日报告"
tr_both "Daily Report Time" "每日报告时间"
tr_both "Device Hours" "设备运行时间"
tr_both "Directory to save PDF reports" "PDF 报告保存目录"
tr_both "Discord Webhook URL" "Discord Webhook URL"
tr_both "Fahrenheit" "华氏度"
tr_both "From Address" "发件地址"
tr_both "Heartbeat Interval (hours)" "心跳间隔（小时）"
tr_both "Hours between heartbeat notifications (default: 24)" "心跳通知间隔小时数（默认：24）"
tr_both "How often to check (default: 5)" "检查频率（默认：5）"
tr_both "Label" "标签"
tr_both "Label (optional)" "标签（可选）"
tr_both "Leave empty for all devices" "留空表示所有设备"
tr_both "Minimum time between repeat notifications per device (0 = use timeout)" "每设备重复通知最小间隔（0 = 使用超时设置）"
tr_both "Monthly Report" "每月报告"
tr_both "Monthly Report Time" "每月报告时间"
tr_both "Seconds between health pushes (default: 60)" "健康推送间隔秒数（默认：60）"
tr_both "Uptime Kuma Push Monitor URL (can also be set in scrutiny.yaml)" "Uptime Kuma 推送监控 URL（也可在 scrutiny.yaml 中设置）"
tr_both "Missed Ping Timeout (minutes)" "心跳超时（分钟）"
tr_both "Config/env URLs cannot be removed from UI" "配置/环境 URL 无法从界面删除"
tr_both "all drives healthy" "所有硬盘健康"
tr_both "Action" "操作"
tr_both "Ignore" "忽略"

# ZFS pool page (chunk-IVE3RJWF)
tr_both "Fragmentation" "碎片率"
tr_both "Last Scrub" "上次清理"
tr_both "Never" "从未"
tr_both "Unknown Pool" "未知池"
tr_both "Error Summary" "错误摘要"
tr_both "In Progress" "进行中"
tr_both "Completed" "已完成"
tr_both "Canceled" "已取消"
tr_both "Failed to load ZFS pool details:" "加载 ZFS 池详情失败："

# ZFS pool delete (chunk-IYE55SBQ)
tr_both "Delete Pool" "删除池"

# NOTE: Do NOT translate underscore attribute names (Raw_Read_Error_Rate, available_spare, etc.)
# They are used as LOOKUP KEYS in the frontend metadata. Translating them breaks the lookup
# and causes all attributes to fall back to "Unknown Attribute Name".
# Display name translations (e.g. "Available Spare" -> "可用备用空间") are already handled above.

# Device detail page - tooltips and labels (chunk-SXF454OX)
tr_chunk_SXF454OX "click for more details." "点击查看详情。"
tr_chunk_SXF454OX "Raw" "原始值"
tr_chunk_SXF454OX "\"Scrutiny\"" "\"Scrutiny 阈值\""

# NOTE: NVMe lowercase underscore names are also lookup keys - do NOT translate them.

# Chart labels
for f in main-*.js chunk-*.js; do
    [ -f "$f" ] || continue
    sed -i 's#"Download SVG"#"下载 SVG"#g' "$f"
    sed -i 's#"Download PNG"#"下载 PNG"#g' "$f"
    sed -i 's#"Download CSV"#"下载 CSV"#g' "$f"
    sed -i 's#exportToSVG#"下载 SVG"#g' "$f"
    sed -i 's#exportToPNG#"下载 PNG"#g' "$f"
done

# MDADM RAID
tr_both "MDADM RAID" "MDADM RAID"
tr_both "RAID Arrays" "RAID 阵列"
tr_both "No MDADM arrays found" "未找到 MDADM 阵列"
tr_both "Ensure the MDADM collector is running and correctly configured." "请确保 MDADM 采集器正在运行且配置正确。"

# Btrfs
tr_both "Btrfs Filesystems" "Btrfs 文件系统"
tr_both "Btrfs filesystem health and topology" "Btrfs 文件系统健康与拓扑"

# Workload description
tr_both "Drive activity rates, intensity, and endurance" "硬盘活动率、强度和耐久度"

# Notify level descriptions
tr_both "Smart = manufacturer failures, Scrutiny = threshold failures, " "Smart = 厂商故障，Scrutiny = 阈值故障，"
tr_both "Warn = notify on warnings and failures, Fail = notify on failures only" "警告 = 通知警告和失败，仅失败 = 仅通知失败"

# Common
tr_both "Not set" "未设置"

# NVMe attribute descriptions
tr_both "Contains the amount of time the controller is busy with I/O commands. The controller is busy when there is a command outstanding to an I/O Queue (specifically, a command was issued via an I/O Submission Queue Tail doorbell write and the corresponding completion queue entry has not been posted yet to the associated I/O Completion Queue). This value is reported in minutes." "包含控制器忙于处理 I/O 命令的时间。当 I/O 队列中有未完成的命令时（即通过 I/O 提交队列尾部门铃写入发出了命令，但相应的完成队列条目尚未发布到关联的 I/O 完成队列），控制器即为忙碌状态。此值以分钟为单位报告。"
tr_both "Contains the amount of time in minutes that the controller is operational and the Composite Temperature is greater the Critical Composite Temperature Threshold (CCTEMP) field in the Identify Controller data structure." "包含控制器运行且复合温度超过识别控制器数据结构中关键复合温度阈值（CCTEMP）字段的时间（以分钟为单位）。"
tr_both "Contains the number of 512 byte data units the host has read from the controller; this value does not include metadata. This value is reported in thousands (i.e., a value of 1 corresponds to 1000 units of 512 bytes read) and is rounded up. When the LBA size is a value other than 512 bytes, the controller shall convert the amount of data read to 512 byte units." "包含主机从控制器读取的 512 字节数据单元数；此值不包括元数据。此值以千为单位报告（即值 1 对应读取 1000 个 512 字节单元）并向上取整。当 LBA 大小不是 512 字节时，控制器应将读取的数据量转换为 512 字节单元。"
tr_both "Contains the number of 512 byte data units the host has written to the controller; this value does not include metadata. This value is reported in thousands (i.e., a value of 1 corresponds to 1000 units of 512 bytes written) and is rounded up. When the LBA size is a value other than 512 bytes, the controller shall convert the amount of data written to 512 byte units." "包含主机写入控制器的 512 字节数据单元数；此值不包括元数据。此值以千为单位报告（即值 1 对应写入 1000 个 512 字节单元）并向上取整。当 LBA 大小不是 512 字节时，控制器应将写入的数据量转换为 512 字节单元。"
tr_both "Contains the number of read commands completed by the controller" "包含控制器完成的读取命令数"
tr_both "Contains the number of write commands completed by the controller" "包含控制器完成的写入命令数"
tr_both "Contains the number of occurrences where the controller detected an unrecovered data integrity error. Errors such as uncorrectable ECC, CRC checksum failure, or LBA tag mismatch are included in this field." "包含控制器检测到不可恢复数据完整性错误的次数。不可纠正的 ECC、CRC 校验和失败或 LBA 标签不匹配等错误包含在此字段中。"
tr_both "Contains the number of Error Information log entries over the life of the controller." "包含控制器生命周期内的错误信息日志条目数。"
tr_both "Contains a vendor specific estimate of the percentage of NVM subsystem life used based on the actual usage and the manufacturer's prediction of NVM life. A value of 100 indicates that the estimated endurance of the NVM in the NVM subsystem has been consumed, but may not indicate an NVM subsystem failure. The value is allowed to exceed 100. Percentages greater than 254 shall be represented as 255. This value shall be updated once per power-on hour (when the controller is not in a sleep state)." "包含基于实际使用情况和制造商 NVM 寿命预测的 NVM 子系统已用寿命百分比（厂商特定估算）。值 100 表示 NVM 子系统中 NVM 的估计耐久度已耗尽，但不一定表示 NVM 子系统故障。此值允许超过 100。超过 254 的百分比应表示为 255。此值应在每次开机时更新一次（当控制器未处于睡眠状态时）。"
tr_both "Contains the number of power-on hours. Power on hours is always logging, even when in low power mode." "包含开机小时数。开机小时数始终记录，即使在低功耗模式下也是如此。"
tr_both "This count is incremented when a shutdown notification (CC.SHN) is not received prior to loss of power." "当断电前未收到关机通知（CC.SHN）时，此计数递增。"

# Scrutiny branding
tr_both "Scrutiny" "Scrutiny"

# Time units
for f in main-*.js chunk-*.js; do
    [ -f "$f" ] || continue
    sed -i 's#" days"#" 天"#g' "$f"
    sed -i 's#" hours"#" 小时"#g' "$f"
    sed -i 's#" minutes"#" 分钟"#g' "$f"
    sed -i 's#" seconds"#" 秒"#g' "$f"
done

# Inline DOM translation script into index.html
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [ -f "index.html" ] && [ -f "${SCRIPT_DIR}/translate_dom.js" ]; then
    # Remove old external script reference if present
    sed -i '/<script src="translate_dom.js"><\/script>/d' index.html
    # Remove old inline script block if present (from previous run)
    sed -i '/^<script>$/,/^<\/script>$/{ /translateStr/d; /translateObj/d; /translateNode/d; /translateElement/d; /translateFullDoc/d; /MutationObserver/d; /DOMContentLoaded/d; /setInterval/d; /origFetch/d; /origXHROpen/d; /origXHRSend/d; /origResponseTextDesc/d; /origResponseDesc/d; /setupDOMTranslation/d; /var T=/d; /Available Spare/d; /Percentage Used/d; /Controller Busy/d; /^<script>$/d; /^<\/script>$/d; }' index.html
    # Inject new inline script
    awk -v script_file="${SCRIPT_DIR}/translate_dom.js" '
        /<\/head>/ {
            print "<script>"
            while ((getline line < script_file) > 0) print line
            print "</script>"
            print
            next
        }
        { print }
    ' index.html > index.html.new && mv index.html.new index.html
    echo "DOM translation script inlined into index.html"
fi

touch "${MARKER}"
echo "Chinese translation applied successfully."
