#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Build
        run: |
          REPO="${{ github.repository }}"
          TAG=$(date +"%Y.%m.%d-%H%M")
          echo "TAG=${TAG}" >> $GITHUB_ENV

          curl -sSL https://static2.fnnas.com/fnpack/fnpack-1.0.4-linux-amd64 -o fnpack
          sudo chmod +x fnpack

          echo "| 应用名称 | 版本 | 平台 | 描述 |" > apps-list.md
          echo "|----------|------|------|------|" >> apps-list.md

          APPS=()
          for APP in fn-*; do
            [ -f "${APP}/norelease" ] && continue
            [ -f "${APP}/manifest" ] || continue
            echo "Building ${APP} ..."

            # ./fnpack create ${APP} --without-ui true  # 如果不需要 UI, 可以启用此行

            APPNAME=$(grep -w '^appname' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            VERSION=$(grep -w '^version' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            DESC=$(grep -w '^desc' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            PLATFORM=$(grep -w '^platform' "${APP}/manifest" | awk -F= '{print $2}' | xargs)

            echo "| ${APPNAME} | v${VERSION} | ${PLATFORM} | ${DESC} |" >> apps-list.md

            if [ -f "${APP}/build.sh" ]; then
              chmod +x "$(realpath "${APP}")/build.sh"
              "$(realpath "${APP}")/build.sh"
              [ $? -ne 0 ] && echo "Build script failed for ${APP}" && exit 1
            else
              ./fnpack build --directory "${APP}"
              mv -f "${APPNAME}.fpk" "${APPNAME}_${PLATFORM}_v${VERSION}.fpk"
              # # 多架构临时对策
              # if [ "${PLATFORM}" = "all" ]; then
              #   for P in x86 arm; do
              #     sed -i "s/= all/= ${P}/" "${APP}/manifest"
              #     ./fnpack build --directory "${APP}"
              #     mv -f "${APPNAME}.fpk" "${APPNAME}_${P}_v${VERSION}.fpk"
              #     sed -i "s/= ${P}/= all/" "${APP}/manifest"
              #   done
              # fi
            fi
            SIZE=$(stat -c%s "${APPNAME}_${PLATFORM}_v${VERSION}.fpk" 2>/dev/null | awk '{printf "%10.3f",$1/1024/1024}' | xargs)
            NAME=$(grep -w '^display_name' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            TYPE=$(grep -w '^install_type' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            distributor=$(grep -w '^distributor' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            distributor_url=$(grep -w '^distributor_url' "${APP}/manifest" | awk -F= '{print $2}' | xargs)
            APPS+=("
          \"${APP}\": {
            \"display_name\": \"${NAME}\",
            \"platform\": \"${PLATFORM}\",
            \"version\": \"${VERSION}\",
            \"desc\": \"${DESC}\",
            \"icon\": \"https://raw.githubusercontent.com/${REPO}/refs/heads/main/${APP}/ICON_256.PNG\",
            \"distributor\": \"${distributor}\",
            \"distributor_url\": \"${distributor_url}\",
            \"bug_report_url\": \"https://github.com/${REPO}/issues\",
            \"labels\": \"工具\",
            \"size\": \"${SIZE}\",
            \"download_url\": \"https://github.com/${REPO}/releases/download/${TAG}/${APPNAME}_${PLATFORM}_v${VERSION}.fpk\",
            \"install_type\": \"$([ "${TYPE}" = "root" ] && echo "系统空间" || echo "存储空间")\",
            \"changelog\": \"Initial release of ${APPNAME} package.\"
          }
          ")
          done

          echo "" >> apps-list.md
          echo "![](https://img.shields.io/github/downloads/${REPO}/${TAG}/total)" >> apps-list.md

          if ! command -v jq >/dev/null 2>&1; then
            sudo apt update >/dev/null 2>&1 && sudo apt install -y jq >/dev/null 2>&1
          fi
          echo {$(IFS=,; echo "${APPS[*]}")} | jq . >fnpack.json

      - name: Check and Push
        if: success()
        run: |
          echo "Git push ..."
          # git checkout main
          git pull
          status=$(git status -s | grep -E "fnpack.json" | awk '{printf " %s", $2}')
          if [ -n "${status}" ]; then
            git add ${status}
            git commit -m "update $(date +%Y-%m-%d" "%H:%M:%S)"
            git push -f
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fn-apps
          path: "*.fpk"
          retention-days: 5

      - name: Release
        if: success() && !cancelled()
        uses: softprops/action-gh-release@v2
        with:
          body_path: "apps-list.md"
          tag_name: ${{ env.TAG }}
          files: |
            *.fpk
